[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
branch = 'main'
version_variable = 'gpt_image/__init__.py:__version__'
build_command = 'python3 -m build'